name: Frontend CI

on:
  push:
    branches: [ main, develop, dev ]
    paths:
      - 'pubspec.yaml'
      - 'lib/**'
      - 'web/**'
      - 'android/**'
      - 'ios/**'
      - 'linux/**'
      - 'macos/**'
      - 'windows/**'
  pull_request:
    branches: [ main, dev ]
    paths:
      - 'pubspec.yaml'
      - 'lib/**'
      - 'web/**'
      - 'android/**'
      - 'ios/**'
      - 'linux/**'
      - 'macos/**'
      - 'windows/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.0'
        channel: 'stable'
    
    - name: Install dependencies
      working-directory: .
      run: flutter pub get
    
    - name: Verify formatting
      working-directory: .
      run: flutter format --output=none --set-exit-if-changed .
    
    - name: Analyze project source
      working-directory: .
      run: flutter analyze
    
    - name: Run tests
      working-directory: .
      run: flutter test
    
    - name: Build web app
      working-directory: .
      run: flutter build web